tektonPipelines:
  workspaces:
    storageClassName: efs-csi
namespace: test
components:
  intelligentTrain:
    git:
      url: https://github.com/Demo-AI-Edge-Crazy-Train/rivieradev-app.git
      contextDir: intelligent-train
      revision: solution
    image:
      #name: quay.io/demo-ai-edge-crazy-train/intelligent-train
      #secretName: quay-authentication
      tag: latest
    createPipelineRun: true
  captureApp:
    git:
      url: https://github.com/Demo-AI-Edge-Crazy-Train/rivieradev-app.git
      contextDir: capture-app
      revision: solution
    image:
      #name: quay.io/demo-ai-edge-crazy-train/train-capture-image-app
      #secretName: quay-authentication
      tag: latest
    createPipelineRun: true
  monitoringApp:
    git:
      url: https://github.com/Demo-AI-Edge-Crazy-Train/rivieradev-app.git
      contextDir: monitoring-app
      revision: solution
    image:
      #name: quay.io/demo-ai-edge-crazy-train/train-monitoring-app
      #secretName: quay-authentication
      tag: latest
    createPipelineRun: true
  ceqApp:
    git:
      url: https://github.com/Demo-AI-Edge-Crazy-Train/rivieradev-app.git
      contextDir: train-ceq-app
      revision: solution
    image:
      #name: quay.io/demo-ai-edge-crazy-train/train-ceq-app
      #secretName: quay-authentication
      tag: latest
    createPipelineRun: true
  trainController:
    git:
      url: https://github.com/Demo-AI-Edge-Crazy-Train/rivieradev-app.git
      contextDir: train-controller
      revision: solution
    image:
      #name: quay.io/demo-ai-edge-crazy-train/train-controller
      #secretName: quay-authentication
      tag: latest
    createPipelineRun: true
